version: "3.9"
services:
  frontend:
    image: nicopaez/password-api:latest
  frontendDos:
    image: nicopaez/password-api:latest    
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    ports:
      - "4000:4000"